core/baux usr/bin/
core/tmux/baux.conf usr/share/baux/tmux/
nvim/init.lua usr/share/baux/nvim/
demo usr/share/baux/
docs usr/share/baux/
forge usr/share/baux/
legacy usr/share/baux/
roxieos usr/share/baux/
test usr/share/baux/
core/tmux/plugins/resurrect usr/share/tmux-plugins/
core/tmux/plugins/continuum usr/share/tmux-plugins/
# TPM — required for system-wide plugins
core/tmux/plugins/tpm usr/share/tmux-plugins/tpm
